title: openSUSE Documentation
title_short: Documentation
email: web@opensuse.org
description: High quality openSUSE documentation for both sysadmins and desktop users.
baseurl: ""
url: ""
weblate_url: https://l10n.opensuse.org/

navbar_links:
  -
    icon: <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-display" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path d="M5.75 13.5c.167-.333.25-.833.25-1.5h4c0 .667.083 1.167.25 1.5H11a.5.5 0 0 1 0 1H5a.5.5 0 0 1 0-1h.75z"/><path fill-rule="evenodd" d="M13.991 3H2c-.325 0-.502.078-.602.145a.758.758 0 0 0-.254.302A1.46 1.46 0 0 0 1 4.01V10c0 .325.078.502.145.602.07.105.17.188.302.254a1.464 1.464 0 0 0 .538.143L2.01 11H14c.325 0 .502-.078.602-.145a.758.758 0 0 0 .254-.302 1.464 1.464 0 0 0 .143-.538L15 9.99V4c0-.325-.078-.502-.145-.602a.757.757 0 0 0-.302-.254A1.46 1.46 0 0 0 13.99 3zM14 2H2C0 2 0 4 0 4v6c0 2 2 2 2 2h12c2 0 2-2 2-2V4c0-2-2-2-2-2z"/></svg>
    text: distros
    children:
      -
        link: /#leap-152
        text: Leap 15.2
      -
        link: /#leap-151
        text: Leap 15.1
      - divider
      -
        link: /archive/#leap-150
        text: Leap 15.0
      -
        link: /archive/#leap-423
        text: Leap 42.3
      -
        link: /archive/#leap-422
        text: Leap 42.2
      -
        link: /archive/#leap-421
        text: Leap 42.1
  -
    icon: <svg width="1em" height="1em" viewBox="0 0 16 16" class="bi bi-tools" fill="currentColor" xmlns="http://www.w3.org/2000/svg"><path fill-rule="evenodd" d="M0 1l1-1 3.081 2.2a1 1 0 0 1 .419.815v.07a1 1 0 0 0 .293.708L10.5 9.5l.914-.305a1 1 0 0 1 1.023.242l3.356 3.356a1 1 0 0 1 0 1.414l-1.586 1.586a1 1 0 0 1-1.414 0l-3.356-3.356a1 1 0 0 1-.242-1.023L9.5 10.5 3.793 4.793a1 1 0 0 0-.707-.293h-.071a1 1 0 0 1-.814-.419L0 1zm11.354 9.646a.5.5 0 0 0-.708.708l3 3a.5.5 0 0 0 .708-.708l-3-3z"/><path fill-rule="evenodd" d="M15.898 2.223a3.003 3.003 0 0 1-3.679 3.674L5.878 12.15a3 3 0 1 1-2.027-2.027l6.252-6.341A3 3 0 0 1 13.778.1l-2.142 2.142L12 4l1.757.364 2.141-2.141zm-13.37 9.019L3.001 11l.471.242.529.026.287.445.445.287.026.529L5 13l-.242.471-.026.529-.445.287-.287.445-.529.026L3 15l-.471-.242L2 14.732l-.287-.445L1.268 14l-.026-.529L1 13l.242-.471.026-.529.445-.287.287-.445.529-.026z"/></svg>
    text: tools
    children:
      -
        link: https://doc.opensuse.org/projects/libzypp/HEAD/
        text: libzypp
      -
        link: https://doc.opensuse.org/projects/libyui/HEAD/
        text: libyui
      - divider
      -
        link: https://openbuildservice.org/help/
        text: Open Build Service
      -
        link: https://open.qa/documentation/
        text: OpenQA
      -
        link: https://osinside.github.io/kiwi/
        text: KIWI NG
      - divider
      -
        link: http://snapper.io/documentation.html
        text: Snapper
      -
        link: http://port.us.org/documentation.html
        text: Portus
      -
        link: https://yast.opensuse.org/documentation
        text: YaST
      -
        link: http://machinery-project.org/docs/
        text: Machinery
  - locales

search_provider: duckduckgo
search_site: doc.opensuse.org

navbar_class: navbar-expand-lg sticky-top

footer_links:
  -
    text: legal_information
    link: https://www.suse.com/company/legal/
  -
    text: source_code
    link: https://github.com/openSUSE/doc.o.o
  -
    text: style_guide
    link: https://documentation.suse.com/style
  -
    text: contact_us
    link: mailto:doc-team@suse.com

leap_versions:
  -
    version: '15.2'
    autoyast: true
  -
    version: '15.1'
    autoyast: true
  -
    version: '15.0'
    end_of_life: true
  -
    version: '42.3'
    end_of_life: true
  -
    version: '42.2'
    end_of_life: true
  -
    version: '42.1'
    end_of_life: true

theme: jekyll-theme-opensuse
markdown: kramdown

plugins:
  - jekyll-locale

exclude: [README.md, LICENSE, Gemfile, Gemfile.lock, vendor]

localization:
  mode       : auto
  locale     : en
  locales_set:
    en:
      name: English
    es:
      name: Español
    fi:
      name: Suomi
    fr:
      name: Français
    zh-CN:
      name: 简体中文
    zh-TW:
      name: 繁體中文
